"""
This type stub file was generated by pyright.
"""

from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from uuid import UUID
from geep_shared_python.schemas import shared_schemas

auth_scheme: HTTPBearer = ...

def convert_to_uuid(ext_dialogue_id: str) -> UUID: ...
def get_user_token_claims(
    token: HTTPAuthorizationCredentials,
) -> shared_schemas.UserTokenClaimsSchema: ...
