"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
logger = ...
_PROBLEMATIC_CONTROL_CHAR_PATTERN = ...

def fix_text_encoding_and_normalise(
    text: str, perform_ftfy: bool = ..., unicode_normalisation_form: str | None = ...
) -> str:
    """
    Fixes common text encoding issues (mojibake) and normalises Unicode text.
    """
    ...

def remove_problematic_control_chars(text: str, replacement: str = ...) -> str:
    """
    Removes problematic control characters from a string while preserving
    common whitespace (Tab, LF, CR).
    """
    ...

def ensure_json_parsable(text: str) -> str:
    """
    Ensures a string that contains JSON can be successfully parsed with json.loads().
    """
    ...

def transliterate_and_force_ascii(text: str) -> str:
    """
    Converts a string to 7-bit ASCII by transliterating with unidecode.
    """
    ...
