"""
This type stub file was generated by pyright.
"""

class ApiRequestException(Exception):
    """Exception raised when creating a dialogue fails."""

    def __init__(self, message: str = ...) -> None: ...
