name: GEEP Shared Python Module CI
run-name: ${{ github.actor }} is running GEEP Shared Python Module CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install poetry
              run: python -m pip install poetry==1.7.1

            - name: Configure poetry
              run: python -m poetry config virtualenvs.in-project true
            
            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v3
              with:
                path: ./.venv
                key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
            
            - name: Install dependencies
              run: poetry install --no-interaction --no-root
              if: steps.cache-deps.outputs.cache-hit != 'true'
            
            - name: Install project
              run: poetry install --no-interaction
            
            - name: Run black formatter
              run: poetry run black --check .
    
            - name: Run flake8 linter
              run: poetry run flake8 .

            - name: Run Pyright type checker
              run: poetry run pyright
          
            - name: Run tests
              run: python -m poetry run python -m pytest -sxv

